spring:
  application:
    name: clinic-staging-admin
  config:
    import: optional:configserver:http://config-server.spring-clinic.svc.cluster.local:8888
    fail-fast: true
    retry:
      initial-interval: 1000
      max-interval: 2000
      max-attempts: 20
  boot:
    admin:
      ui:
        title: PetClinic Admin
      discovery:
        enabled: true
      client:
        url: http://clinic-staging-admin.spring-clinic-staging.svc.cluster.local:9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://clinic-staging-discovery.spring-clinic-staging.svc.cluster.local:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
server:
  shutdown: graceful
---
spring:
  config:
    activate:
      on-profile: kubernetes
  cloud:
    config:
      allow-override: true
      override-none: true