spring:
  application:
    name: admin-server
  boot:
    admin:
      ui:
        title: PetClinic Admin
      discovery:
        enabled: true
      client:
        url: http://admin-server.spring-petclinic-staging.svc.cluster.local:9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://clinic-staging-discovery.spring-clinic-staging.svc.cluster.local:8761/eureka/