server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: customers-service
          uri: lb://customers-service.spring-petclinic-staging.svc.cluster.local
          predicates:
            - Path=/api/customer/**
        - id: visits-service
          uri: lb://visits-service.spring-petclinic-staging.svc.cluster.local
          predicates:
            - Path=/api/visit/**
        - id: vets-service
          uri: lb://vets-service.spring-petclinic-staging.svc.cluster.local
          predicates:
            - Path=/api/vet/**
        - id: api-gateway
          uri: lb://api-gateway.spring-petclinic-staging.svc.cluster.local
          predicates:
            - Path=/api/gateway/**

  config:
    activate:
      on-profile: kubernetes
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server.spring-petclinic-staging.svc.cluster.local:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0