server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: clinic-staging-vets
          uri: http://clinic-staging-vets.spring-clinic-staging.svc.cluster.local:8083
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: clinic-staging-visits
          uri: http://clinic-staging-visits.spring-clinic-staging.svc.cluster.local:8082
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: clinic-staging-customer
          uri: http://clinic-staging-customer.spring-clinic-staging.svc.cluster.local:8081
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
        - id: clinic-staging-genai
          uri: http://clinic-staging-genai.spring-clinic-staging.svc.cluster.local:8084
          predicates:
            - Path=/api/genai/**

  config:
    activate:
      on-profile: kubernetes
eureka:
  client:
    serviceUrl:
      defaultZone: http://clinic-staging-discovery.spring-clinic-staging.svc.cluster.local:8761/eureka/
    registryFetchIntervalSeconds: 10
    instanceInfoReplicationIntervalSeconds: 10
    initialInstanceInfoReplicationIntervalSeconds: 30
  instance:
    hostname: clinic-staging-apigateway.spring-clinic-staging.svc.cluster.local
    prefer-ip-address: false
    metadata-map:
      namespace: spring-clinic-staging
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  logging:
    level:
      com.netflix.discovery: DEBUG
      org.springframework.cloud.gateway: DEBUG
      org.springframework.cloud.netflix.eureka: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0