server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: clinic-staging-vets
          uri: lb://clinic-staging-vets.spring-clinic-staging.svc.cluster.local
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: clinic-staging-visits
          uri: lb://clinic-staging-visits.spring-clinic-staging.svc.cluster.local
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: clinic-staging-customer
          uri: lb://clinic-staging-customer.spring-clinic-staging.svc.cluster.local
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
        - id: clinic-staging-genai
          uri: lb://clinic-staging-genai.spring-clinic-staging.svc.cluster.local
          predicates:
            - Path=/api/genai/**

  config:
    activate:
      on-profile: kubernetes
eureka:
  client:
    serviceUrl:
      defaultZone: http://clinic-staging-discovery.spring-clinic-staging.svc.cluster.local:8761/eureka/
    registryFetchIntervalSeconds: 10
    instanceInfoReplicationIntervalSeconds: 10
    initialInstanceInfoReplicationIntervalSeconds: 30
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0