server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
        - name: Retry
          args:
            retries: 1
            statuses: SERVICE_UNAVAILABLE
            methods: POST
      routes:
        - id: vets-service
          uri: http://clinic-staging-vets.spring-clinic-staging.svc.cluster.local:8083
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: http://clinic-staging-visits.spring-clinic-staging.svc.cluster.local:8082
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: http://clinic-staging-customer.spring-clinic-staging.svc.cluster.local:8081
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
        - id: genai-service
          uri: http://clinic-staging-genai.spring-clinic-staging.svc.cluster.local:8084
          predicates:
            - Path=/api/genai/**
          filters:
            - StripPrefix=2
            - CircuitBreaker=name=genaiCircuitBreaker,fallbackUri=/fallback

  config:
    activate:
      on-profile: kubernetes
eureka:
  client:
    serviceUrl:
      defaultZone: http://clinic-staging-discovery.spring-clinic-staging.svc.cluster.local:8761/eureka/
    registryFetchIntervalSeconds: 10
    instanceInfoReplicationIntervalSeconds: 10
    initialInstanceInfoReplicationIntervalSeconds: 30
  instance:
    hostname: clinic-staging-apigateway.spring-clinic-staging.svc.cluster.local
    prefer-ip-address: false
    metadata-map:
      namespace: spring-clinic-staging
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  logging:
    level:
      com.netflix.discovery: DEBUG
      org.springframework.cloud.gateway: DEBUG
      org.springframework.cloud.netflix.eureka: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0