spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://config-server.spring-clinic.svc.cluster.local:8888
    fail-fast: true
    retry:
      initial-interval: 1000
      max-interval: 2000
      max-attempts: 20
  cloud:
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
        - name: Retry
          args:
            retries: 1
            statuses: SERVICE_UNAVAILABLE
            methods: POST
      routes:
        - id: clinic-staging-vets
          uri: lb://clinic-staging-vets
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: clinic-staging-visits
          uri: lb://clinic-staging-visits
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: clinic-staging-customer
          uri: lb://clinic-staging-customer
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
        - id: clinic-staging-genai
          uri: lb://clinic-staging-genai
          predicates:
            - Path=/api/genai/**
          filters:
            - StripPrefix=2
            - CircuitBreaker=name=genaiCircuitBreaker,fallbackUri=/fallback
eureka:
  client:
    serviceUrl:
      defaultZone: http://clinic-staging-discovery.spring-clinic-staging.svc.cluster.local:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
server:
  shutdown: graceful
---
spring:
  config:
    activate:
      on-profile: kubernetes
  cloud:
    config:
      allow-override: true
      override-none: true
