spring:
  application:
    name: api-gateway
  cloud:
    config:
      allow-override: true
      override-none: true
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
        - name: Retry
          args:
            retries: 3
            statuses: SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
            methods: GET, POST
      routes:
        - id: clinic-staging-customer
          uri: lb://clinic-staging-customer
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
        - id: clinic-staging-vets
          uri: lb://clinic-staging-vets
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: clinic-staging-visits
          uri: lb://clinic-staging-visits
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: clinic-staging-genai
          uri: lb://clinic-staging-genai
          predicates:
            - Path=/api/genai/**
          filters:
            - StripPrefix=2
            - CircuitBreaker=name=genaiCircuitBreaker,fallbackUri=/fallback
  sleuth:
    sampler:
      probability: 1.0
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  zipkin:
    base-url: http://clinic-staging-zipkin.spring-clinic-staging.svc.cluster.local:9411/
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://clinic-staging-discovery.spring-clinic-staging.svc.cluster.local:8761/eureka/
    registryFetchIntervalSeconds: 10
    instanceInfoReplicationIntervalSeconds: 10
    initialInstanceInfoReplicationIntervalSeconds: 30
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
---
spring:
  config:
    activate:
      on-profile: kubernetes,docker
    import: configserver:http://config-server.spring-clinic.svc.cluster.local:8888