# COMMON APPLICATION PROPERTIES

server:
  port: 0  # Random port for Docker compatibility
  shutdown: graceful  # Graceful shutdown for handling existing requests

spring:
  application:
    name: spring-clinic
  cloud:
    config:
      allow-override: true
      override-none: true
  sleuth:
    sampler:
      probability: 1.0
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  zipkin:
    base-url: http://clinic-staging-zipkin.spring-clinic-staging.svc.cluster.local:9411/
    enabled: true
  sql:
    init:
      schema-locations: classpath*:db/hsqldb/schema.sql
      data-locations: classpath*:db/hsqldb/data.sql
      mode: ALWAYS  # Initialize database on startup
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://mysql:3306/petclinic?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: petclinic

eureka:
  client:
    serviceUrl:
      defaultZone: http://clinic-staging-discovery.spring-clinic-staging.svc.cluster.local:8761/eureka/
    registryFetchIntervalSeconds: 10
    instanceInfoReplicationIntervalSeconds: 10
    initialInstanceInfoReplicationIntervalSeconds: 30
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

# Logging
logging:
  level:
    org.springframework: INFO

# Metrics and Monitoring
management:
  security:
    enabled: false  # Disable actuator security
  endpoints:
    web:
      exposure:
        include: '*'  # Expose all actuator endpoints
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

# Chaos Engineering (optional profile)
---
spring:
  config:
    activate:
      on-profile: chaos-monkey
management:
  endpoint:
    chaosmonkey:
      enabled: true
chaos:
  monkey:
    enabled: true
    watcher:
      component: false
      controller: false
      repository: false
      rest-controller: false
      service: false

# MySQL profile (already included in main config for Docker)
---
spring:
  config:
    activate:
      on-profile: mysql
  sql:
    init:
      schema-locations: classpath*:db/mysql/schema.sql
      data-locations: classpath*:db/mysql/data.sql
      mode: ALWAYS