spring:
  application:
    name: discover-server
  config:
    import: configserver:http://config-server.spring-clinic.svc.cluster.local:8888
    fail-fast: true
    retry:
      initial-interval: 1000
      max-interval: 2000
      max-attempts: 20
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://clinic-staging-discovery.spring-clinic-staging.svc.cluster.local:8761/eureka/
---
spring:
  config:
    activate:
      on-profile: kubernetes
    import: configserver:http://config-server.spring-clinic.svc.cluster.local:8888