vets:
  cache:
    ttl: 60
    heap-size: 100

spring:
  config:
    activate:
      on-profile: kubernetes
  datasource:
    url: jdbc:mysql://mysql.spring-petclinic-staging.svc.cluster.local:3306/petclinic?allowPublicKeyRetrieval=true&useSSL=false
    username: petclinic
    password: petclinic

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server.spring-petclinic-staging.svc.cluster.local:8761/eureka/

server:
  port: 8083