vets:
  cache:
    ttl: 60
    heap-size: 100

spring:
  application:
    name: vets-service
  config:
    activate:
      on-profile: kubernetes
  datasource:
    url: jdbc:mysql://mysql.spring-petclinic-staging.svc.cluster.local:3306/petclinic?allowPublicKeyRetrieval=true&useSSL=false
    username: petclinic
    password: petclinic
  zipkin:
    base-url: http://clinic-staging-zipkin.spring-clinic-staging.svc.cluster.local:9411
    enable: true

eureka:
  instance:
    hostname: clinic-staging-vets.spring-clinic-staging.svc.cluster.local
    prefer-ip-address: false
    metadata-map:
      namespace: spring-clinic-staging
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://clinic-staging-discovery.spring-petclinic-staging.svc.cluster.local:8761/eureka/
management:
  zipkin:
    tracing:
      endpoint: http://clinic-staging-zipkin.spring-clinic-staging.svc.cluster.local:9411/api/v2/spans

server:
  port: 8083