spring:
  application:
    name: visits-service
  config:
    activate:
      on-profile: kubernetes
  datasource:
    url: jdbc:mysql://mysql.spring-petclinic-staging.svc.cluster.local:3306/petclinic?allowPublicKeyRetrieval=true&useSSL=false
    username: petclinic
    password: petclinic
  zipkin:
    base-url: http://clinic-staging-zipkin.spring-clinic-staging.svc.cluster.local:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://clinic-staging-discovery.spring-petclinic-staging.svc.cluster.local:8761/eureka/
  instance:
    hostname: clinic-staging-visits.spring-clinic-staging.svc.cluster.local
    prefer-ip-address: false
    metadata-map:
      namespace: spring-clinic-staging
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  server:
    enable-self-preservation: true
    peer-node-read-timeout-ms: 10000
    response-cache-update-interval-ms: 30000
management:
  zipkin:
    tracing:
      endpoint: http://clinic-staging-zipkin.spring-clinic-staging.svc.cluster.local:9411/api/v2/spans
server:
  port: 8082